export const GET_DISCOVER_MOVIES = 'GET_DISCOVER_MOVIES';

export const GET_TV_MOVIES = 'GET_TV_MOVIES';

export const GET_TRENDING_MOVIES = 'GET_TRENDING_MOVIES';

export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL';

export const GET_SEARCH_MOVIES = 'GET_SEARCH_MOVIES';
